### PR TITLE
Retrooper

### LINKED ISSUE #46: You forgot something
You forgot to add KennyTV on the list of shame.

### PR DESCRIPTION
**Pull request by mdcfe**
Fixes #46

### CODE REVIEW

**Review by KennyTV — APPROVED** [review]
pufferfish

**Comment by retrooper** [comment]
:disappointed:

**Comment by retrooper** [comment]
lol

**Comment by Aberdeener** [comment]
Thank you

**Comment by mdcfe** [comment]
> Thank you

@Aberdeener Glad to be of service to the community!

**Pull request merged**
