### PR TITLE
Add Intellij IDEA

### PR DESCRIPTION
**Pull request by Fox2Code**
Hopefully it is still possible to disable Intellij IDEA from asking me to use lambda and streams, and I no longer become an impostor for using `Map.put(key, value)`.
But this make this tool a bad tool for beginner because it teach bad code practices.

See #81 for context.

### CODE REVIEW

**Comment by KaspianDev** [comment]
+ its slow

**Comment by andriycraft** [comment]
also add eclipse, it sucks

**Comment by Andre601** [comment]
> also add eclipse, it sucks

That's a subjective thing if you ask me.
Some of the best plugins out there were made in Eclipse. Like PlaceholderAPI's original maintainer (extended_clip) did use Eclipse for it. And BKCommonLib and plugins using it like TrainCarts also are developed using Eclipse.

In general, whether an IDE is good or bad comes down to personal taste and experience. A good enough dev could create stuff using a normal notepad program.
So adding this IDE (And others) would not really be a somewhat objective thing here.

**Comment by andriy332** [comment]
> * its slow

no

**Comment by andriy332** [comment]
> Eclipse really sucks
> 
> 1. Lags
> 2. Bugs with encoding
> 3. Can randomly crash

4. some of open files will be corrupted after crash

**Comment by MyrsujV2** [comment]
> vim is best

yes

**Comment by Wesley51** [comment]
This is a minecraft related list of shame. IntelliJ isn't minecraft related except people use it to develop plugins.

**Comment by Fox2Code** [comment]
Closing because I'm not willing to contribute to a project sharing blatant misinformation.

https://github.com/kennytv/list-of-shame/commit/0bd3e4e5a3b793f0e0e9c2699de085b20224af35 statement is completely destroyed [by this video](https://www.youtube.com/watch?v=DobmW1ZUcbQ)

This repo just became a political tool for kenytv, I'm no longer interested in participating in this.

**Comment by JRoy** [comment]
> Closing because I'm not willing to contribute to a project sharing blatant misinformation.
> 
> https://github.com/kennytv/list-of-shame/commit/0bd3e4e5a3b793f0e0e9c2699de085b20224af35 statement is completely destroyed [by this video](https://www.youtube.com/watch?v=DobmW1ZUcbQ)
> 
> This repo just became a political tool for kenytv, I'm no longer interested in participating in this.

You are incredibly stupid

**Pull request closed without merging**
